version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: ./apps/web
    ports:
      - "3000:2001"
    depends_on:
      - db

  backend:
    build: ./apps/web/backend
    ports:
      - "1337:2002"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db/mydb

volumes:
  db-data:
